### ISSUE TITLE
npm start: startup fails

### ISSUE THREAD

**Issue by HansS** [mousetraps/bobblehead#1]
Hans@HP-HANS C:\Users\Hans\Web\bootcamps\mva\bobblehead

> node -v
> v0.12.7

Hans@HP-HANS C:\Users\Hans\Web\bootcamps\mva\bobblehead

> npm -v
> 2.11.3

Hans@HP-HANS C:\Users\Hans\Web\bootcamps\mva\bobblehead

> npm start
> 
> bobblehead@0.0.0 start C:\Users\Hans\Web\bootcamps\mva\bobblehead
> node ./bin/www

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\Hans\Web\bootcamps\mva\bobblehead\bin\www'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! bobblehead@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bobblehead@0.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the bobblehead package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls bobblehead
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Hans\Web\bootcamps\mva\bobblehead\npm-debug.log

npm-debug.log:

> type npm-debug.log
> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\Program Files\nodejs\\node.exe',
> 1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
> 1 verbose cli   'start' ]
> 2 info using npm@2.11.3
> 3 info using node@v0.12.7
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info prestart bobblehead@0.0.0
> 6 info start bobblehead@0.0.0
> 7 verbose unsafe-perm in lifecycle true
> 8 info bobblehead@0.0.0 Failed to exec start script
> 9 verbose stack Error: bobblehead@0.0.0 start: `node ./bin/www`
> 9 verbose stack Exit status 1
> 9 verbose stack     at EventEmitter.<anonymous> (C:\Users\Hans\AppData\Roaming\nvm\v0.12.7\node_modules\npm\lib\utils\lifecycle.js:213:16)
> 9 verbose stack     at EventEmitter.emit (events.js:110:17)
> 9 verbose stack     at ChildProcess.<anonymous> (C:\Users\Hans\AppData\Roaming\nvm\v0.12.7\node_modules\npm\lib\utils\spawn.js:24:14)
> 9 verbose stack     at ChildProcess.emit (events.js:110:17)
> 9 verbose stack     at maybeClose (child_process.js:1015:16)
> 9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
> 10 verbose pkgid bobblehead@0.0.0
> 11 verbose cwd C:\Users\Hans\Web\bootcamps\mva\bobblehead
> 12 error Windows_NT 6.3.9600
> 13 error argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
> 14 error node v0.12.7
> 15 error npm  v2.11.3
> 16 error code ELIFECYCLE
> 17 error bobblehead@0.0.0 start: `node ./bin/www`
> 17 error Exit status 1
> 18 error Failed at the bobblehead@0.0.0 start script 'node ./bin/www'.
> 18 error This is most likely a problem with the bobblehead package,
> 18 error not with npm itself.
> 18 error Tell the author that this fails on your system:
> 18 error     node ./bin/www
> 18 error You can get their info via:
> 18 error     npm owner ls bobblehead
> 18 error There is likely additional logging output above.
> 19 verbose exit [ 1, true ]

**Comment by mousetraps** [comment]
Ahh probably forgot to push some local changes - Set the startup script to app.js instead of bin/www and you should be set.

**Comment by HansS** [comment]
changed to : node app.js
get error with a image.jpg upload trial:
"Error: ENOENT, open 'C:\Users\Hans\Web\bootcamps\mva\bobblehead\uploads\userPhoto-1449317562939.jpg'

I also would like to remove the crazy cat running over the screen!

**Comment by HansS** [comment]
Hi Sarah,
changed startup to : node apperror:Error: ENOENT, open 'C:\Users\Hans\Web\bootcamps\mva\bobblehead\uploads\userPhoto-1449317562939.jpg'
I would also like to remove the noisy crazy cat running over the screen!
kind regardsHans

Date: Sat, 5 Dec 2015 01:35:00 -0800

**Comment by mousetraps** [comment]
pushed some changes. should work better now but lmk if you run into any more issues. also made the cats an option :smiley:

**Comment by HansS** [comment]
Hi Sara,
thank's a lot.I appreciate your work and passion for Node.js inside Microsoft!
kind regardsHans

Date: Thu, 10 Dec 2015 15:09:44 -0800
